trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install html2text
      python scripts/generate_markdown.py
    displayName: 'Générer la documentation Markdown'

  - task: Bash@3
    displayName: 'Copier les fichiers Markdown dans le Wiki'
    inputs:
      targetType: 'inline'
      script: |
        git clone https://${AZURE_DEVOPS_PAT}@dev.azure.com/Willimath/Willimath%20API/_git/Wiki
        cp -r docs/*.md wiki/
        cd wiki
        git add .
        git commit -m "Mise à jour automatique des fichiers Markdown"
        git push
