version: '3.8'

services:
  postgres:
    doc: emmeuhnez-moi-api
    container_name: emmeuhnez-moi
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"